### ISSUE TITLE
Use `import()` instead of `require()` for commonjs/esmodule support

### ISSUE THREAD

**Issue by jasikpark** [CodeIntelligenceTesting/jazzer.js#162]
I'm trying to get a fuzz harness set up for https://github.com/natemoo-re/ultrahtml but I'm running into a problem with the fact that the module is written as an esmodule instead of a commonjs module

It'd be great if `jazzer.js` supported es modules natively, ex:

```js
export function fuzz() {}
```
instead of `module.exports.fuzz = function() {}` or using TS to generate commonjs

https://github.com/jasikpark/fuzz-ultrahtml

**Comment by bertschneider** [comment]
Actually, we already worked on this, but it didn't make it into the `main` branch. This issue is a good reminder to continue switching over to `import`.

In the meantime you could try out the version on branch `es-module-import`.

**Comment by jasikpark** [comment]
Oooh, great! Not having es module support has been one of the initial problems for me trying to use this and jsfuzz w/ es module packages w/o bundling them fully

**Comment by bertschneider** [comment]
We just merged a first step towards general ESM support. The remaining quirk is the instrumentation of ESM files, as intercepting loaded code requires custom Node.js loaders. We will continue to investigate this, though.

In the meantime, could you please try out the current version on `main`? The next release will probably be due early next year.

**Comment by jasikpark** [comment]
I'll close this as https://github.com/jasikpark/fuzz-prettier is using the typescript jest integration happily, import ESM packages as well 👍
