### ISSUE TITLE
Istanbul Report From Jazzer Js

### ISSUE THREAD

**Issue by harisab2547** [CodeIntelligenceTesting/jazzer.js#481]
Would I be able to generate the Istanbul report in which i get the knowledge of code coverage?

**Comment by oetr** [comment]
Yes, just use the --coverage flag.

**Comment by harisab2547** [comment]
I have used the flag but no coverage folder is generated and also I tried to give custom folder path(--cov_dir=test_fuzz) which also didn't work

**Comment by oetr** [comment]
Can you provide an example so that we can reproduce this issue?

**Comment by bertschneider** [comment]
Closing this issue for now. Please feel free to reopen once you can reproduce it.

**Comment by harisab2547** [comment]
Yes, you are right it was generating the report,
Thank you.
I was running the commands on powershell but when I switched to CMD it started generating the report.
Thanks
