### ISSUE TITLE
CLi crash when calling with numerical fuzzingEngineFlags

### ISSUE THREAD

**Issue by tstehr** [CodeIntelligenceTesting/jazzer.js#531]
The CLI crashes ungracefully when trying to pass an argument that looks numerical to the `fuzzingEngineFlags`. I discovered this while trying to pass `-max_total_time 60` to `libFuzzer`. 

Note that this was a typo on my side, the correct argument is `-max_total_time=60`

To reproduce, run the following:

```
> yarn run jazzer fuzz.js corpus -- -max_total_time 60
==71008== Uncaught Exception: Jazzer.js: flag.startsWith is not a function
TypeError: flag.startsWith is not a function
    at /project/node_modules/@jazzer.js/core/core.ts:188:9
    at Array.some (<anonymous>)
    at prepareLibFuzzerArg0 (/project/node_modules/@jazzer.js/core/core.ts:186:47)
    at buildFuzzerOptions (/project/node_modules/@jazzer.js/core/core.ts:380:10)
    at startFuzzingNoInit (/project/node_modules/@jazzer.js/core/core.ts:172:24)
    at startFuzzing (/project/node_modules/@jazzer.js/core/core.ts:138:8)
```

The underlying issue seems to be [yargs silently converting numerical-looking arguments into numbers](https://github.com/yargs/yargs/blob/main/docs/tricks.md#numbers).

**Comment by bertschneider** [comment]
Thanks for the bug report and analysis! As we're in the process of streamlining parameter handling and already changed quite a bit of code in that area, I added a fix directly to #530 to prevent complicated merge conflicts.

In the future this situation should print a message like:
```
WARNING: unrecognized flag '-max_total_time'; use -help=1 to list all flags

ERROR: The required directory "10" does not exist
```
Admittedly not the nicest one but it should point to the problem good enough.
