### ISSUE TITLE
Several "build" dependencies as runtime dependencies?

### ISSUE THREAD

**Issue by karfau** [CodeIntelligenceTesting/jazzer.js#642]
When installing `@jazzer.js/core` v2.0, 63 dependencies are added.
When inspecting the graph, e.g. using https://npmgraph.js.org/?q=%40jazzer.js%2Fcore#zoom=h
i can spot at least two "areas" that look like they might not be required to run fuzz tests, since they are usually only required when "building stuff"
- `@jazzer.js/fuzzer` depends on `cmake-js`
- `@jazzer.js/hooking` and `@jazzer.js/instrumentor` depend on `@babel/core` (with tons of transient dependencies)

Are they really required to execute fuzzing or should those be devDependencies?

**Comment by oetr** [comment]
- `@babel/core`: @jazzer.js/hooking does not depend on @babel/core and can be completely removed as a dependency. Good catch :+1:
- `@babel/core`: @jazzer.js/instrumentor needs it to work properly
- `cmake-js` : in case that the target system cannot use our pre-built release, it will build our fork of libfuzzer locally
