### ISSUE TITLE
Error when installing fuzz @jazzer.js/core

### ISSUE THREAD

**Issue by PoppingSnack** [CodeIntelligenceTesting/jazzer.js#771]
When I followed instruction `npm install --save-dev @jazzer.js/core` to install jazzer.js, I got the following error. 
Please tell me why and how to solve it.
System：win10
nodejs：v18.19.0
npm: 10.2.3

```
D:\test\ci-fuzz-cli-tutorials-main\js_ts\nodejs-js>npm install --save-dev @jazzer.js/core
npm ERR! code 1
npm ERR! path D:\test\ci-fuzz-cli-tutorials-main\js_ts\nodejs-js\node_modules\@jazzer.js\fuzzer
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c prebuild-install --runtime napi || npm run prebuild
npm ERR! > @jazzer.js/fuzzer@2.1.0 prebuild
npm ERR! > prebuild --runtime napi --backend cmake-js --all --strip --verbose
npm ERR! prebuild-install warn install unable to verify the first certificate
npm ERR! 'prebuild' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
npm ERR! ���������ļ���
```

**Comment by bertschneider** [comment]
Jazzer.js requires a prebuild native binary, which is downloaded from GitHub during the installation phase. The error message looks like a network issue caused by a proxy, could that be the case? Please try to lookup the error message in combination with `npm`, there are quite some problem reports.
